# model configuration
model_name_or_path: "data/model"

# dataset configuration
data_path: "data/iwslt2017-en-de"
cache_dir: "data/cache"
num_proc: 1

# training configuration
seed: 42
# train
do_train: true
output_dir: "data/output"
bf16: true
# deepspeed: "deepspeed_configs/ds_z2_config.json"
num_train_epochs: 2
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
optim: adamw_torch
learning_rate: 8.0e-5
lr_scheduler_type: cosine
warmup_steps: 100
logging_steps: 1
save_strategy: "steps"
save_steps: 500
report_to: "tensorboard"
# validation
do_eval: true
per_device_eval_batch_size: 8
eval_steps: 100
